### ISSUE TITLE
Problem with LSTM_extract.py I

### ISSUE THREAD

**Issue by MarioRinBarr** [weir12/DENA#24]
Hello,
I am trying to use DANA. In step one, with LSTM_extract.py I get the following error, and I don't know why. I am using the command line of your tutorial, adapted to my data:

Traceback (most recent call last):
  File "/home/mario/Programas/DENA/DENA-release/step4_predict/LSTM_extract.py", line 21, in <module>
    from tombo import tombo_helper, tombo_stats, resquiggle
  File "/home/mario/anaconda3/lib/python3.11/site-packages/tombo/tombo_stats.py", line 84, in <module>
    HALF_NORM_EXPECTED_VAL = stats.halfnorm.expect()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mario/anaconda3/lib/python3.11/site-packages/scipy/stats/_distn_infrastructure.py", line 2914, in expect
    dub = integrate.quad(fun, d, ub, **kwds)[0]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mario/anaconda3/lib/python3.11/site-packages/scipy/integrate/_quadpack_py.py", line 465, in quad
    retval = _quad(func, a, b, args, full_output, epsabs, epsrel, limit,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mario/anaconda3/lib/python3.11/site-packages/scipy/integrate/_quadpack_py.py", line 579, in _quad
    return _quadpack._qagie(func,bound,infbounds,args,full_output,epsabs,epsrel,limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mario/anaconda3/lib/python3.11/site-packages/scipy/stats/_distn_infrastructure.py", line 2891, in fun
    return x * self.pdf(x, *args, **lockwds)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mario/anaconda3/lib/python3.11/site-packages/scipy/stats/_distn_infrastructure.py", line 1992, in pdf
    place(output, cond, self._pdf(*goodargs) / scale)
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/mario/anaconda3/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py", line 4253, in _pdf
    return np.sqrt(2.0/np.pi)*np.exp(-x*x/2.0)
                              ^^^^^^^^^^^^^^^^
FloatingPointError: underflow encountered in exp

**Comment by weir12** [comment]
Hello,

Thank you for reaching out and detailing the issue you're experiencing with DENA when using LSTM_extract.py, specifically the part where it integrates with Tombo and results in a FloatingPointError: underflow encountered in exp. From the traceback you provided, it's clear that this error occurs deep within the Tombo and SciPy libraries, suggesting that the problem might be related to the handling of extreme values by Tombo's dependencies.

Given that the error originates from Tombo's use of the SciPy library, I recommend reaching out to the Tombo maintainers for more specialized assistance. It's possible that they have encountered similar reports or could offer insights into whether this represents an edge case in their processing pipeline or a more systemic issue that needs addressing.

When creating an issue on the Tombo GitHub repository, it would be helpful to include:

A detailed description of the problem, including the full error traceback.
The specific command or code snippet you're using, adapted for your data.
The version of Tombo you are using, along with your Python version and operating system details.
A brief description of your dataset, especially if there are unique characteristics that might be pertinent to the issue.
